### ISSUE TITLE
Hooks sets localStorage value to string 'undefined' rather than doing nothing.

### ISSUE THREAD

**Issue by AlexLeung** [astoilkov/use-local-storage-state#30] opened 2021-09-14 01:19 UTC
```typescript
const [storedData, setStoredData, { removeItem }] = useLocalStorageState("testing");
const value = localStorage.getItem('testing')
console.log(typeof value);
console.log(value)
```
this outputs
```
string
undefined
```
this should ideally output
```
object
null
```
Why is the hook updating local storage when the client code never instructs it to do so?

**Comment by astoilkov** [comment] 2021-09-14 06:54
This is caused by the change that was made when resolving https://github.com/astoilkov/use-local-storage-state/issues/26.

Probably I should not write the value on the initial render when a value isn't passed.

**Closed** 2021-09-14 09:59 UTC

**Comment by astoilkov** [comment] 2021-11-12 19:44
I just made a new release that includes the change. Thanks for reporting!
