### ISSUE TITLE
Handle error when localStorage value is not JSON parseable

### ISSUE THREAD

**Issue by pacocoursey** [astoilkov/use-local-storage-state#2] opened 2020-04-01 21:14 UTC
If a localStorage value is manually set (not through the hook) and is not valid JSON syntax, this library will throw an error when attempting to parse it:

```
Uncaught SyntaxError: Unexpected token a in JSON at position 0
```

Ideally, the hook should handle this error gracefully, in the case that another piece of code overrides the value or it is edited manually through dev tools.

Places to error check:

https://github.com/astoilkov/use-local-storage-state/blob/0a24bb51486abaee6860838e593b2e4e937b5787/index.ts#L47

https://github.com/astoilkov/use-local-storage-state/blob/0a24bb51486abaee6860838e593b2e4e937b5787/index.ts#L11

**Comment by astoilkov** [comment] 2020-04-11 18:21
Sorry, for the delayed response. I wasn't watching the repository for some strange reason and I didn't receive a notification or an email for your issue.

I intentionally left out the `try/catch` logic of handling JSON parsing errors. This follows a programming principle I have: **Don't add code before you know why**.

I couldn't figure out what should happen that the programmer can't or didn't handle for this to happen. And if there is such a case isn't it better to throw an error? Because I couldn't figure out the answers to those questions I left it out so people can share their scenarios.

Do you have a scenario that we can discuss and find out the right answer?

**Comment by igorbarbashin** [comment] 2020-04-21 19:47
I also had a similar issue. I thought that in order to delete a local storage item I'd just pass `undefined` as value.
But it then was stored as `"undefined"` string and then was unable to parse.

What is the best way to remove an item? Just by calling `window.localStorage.removeItem()`?

**Comment by astoilkov** [comment] 2020-04-22 12:22
The `undefined` case is very confusing indeed. I will change this behavior and introduce a new version.

Until then you can use DevTools Console and run `localStorage.removeItem()` or DevTools Application Local Storage where you can manage the data in local storage.

**Comment by rexxars** [comment] 2020-04-26 20:25
I've encountered this. When you're not following your good advise on namespacing keys, it's possible (and potentially likely) that you may be using a key that some other app might also be using. In this case, their data may not be JSON and thus crash.

The obvious solution to this is to use namespaced keys, but having a way to gracefully recover would be nice. Maybe use the default value and do a `console.warn`?

**Comment by astoilkov** [comment] 2020-04-27 07:37
@rexxars Thank you for the suggestion. I will work on the problem this week and ask you for ideas.

**Comment by astoilkov** [comment] 2020-04-28 18:39
@rexxars What do you mean by "some other app"? Did you encounter the error while developing? On encountering the error was it confusing for you to understand why the error was happening?

Thanks.

**Comment by rexxars** [comment] 2020-04-28 20:07
While developing locally, apps tend to use similar port numbers (eg `:3000`), and you can easily end up with competing localstorage keys. If the competing key isn't a JSON-encoded string, it'll throw. If you have a competing key which _is_ JSON encoded, you can of course end up with some _really_ weird results, but that's hard to guard against ;)

**Comment by chasemccoy** [comment] 2020-06-20 03:28
I ran into this issue as well 👋 any updates?

**Comment by astoilkov** [comment] 2020-06-20 09:38
@chasemccoy What version are you using? The latest version handles errors caused by `JSON.parse()` — https://github.com/astoilkov/use-local-storage-state/blob/master/index.ts#L15-L19

**Comment by chasemccoy** [comment] 2020-06-20 19:08
@astoilkov I installed the latest version (`3.0.1`) and I tried to hook it up to a component with a local storage key that had already been assigned a value (in this case, the value was a plain string) and received this error. Everything was fine after switching to a new key or deleting the old key

**Comment by astoilkov** [comment] 2020-06-22 13:46
@chasemccoy I decided to write a test case for this scenario – https://github.com/astoilkov/use-local-storage-state/blob/master/test.ts#L59-L66 which successfully passes. Maybe the problem is more complicated.

Can you create and share an example that successfully replicates the problem?

**Comment by chasemccoy** [comment] 2020-06-22 14:57
@astoilkov Hmm... I can't seem to reproduce the issue now! I'll keep trying, but perhaps I just had some sort of edge case? Either way, thank you for investigating!

**Comment by astoilkov** [comment] 2020-10-12 12:49
I have thought a lot about this. I decided to put everything in place so the library doesn't throw any errors. The new 5.1.0 release includes everything needed. Hope you like the change. Thanks to everybody who shared your opinion.

I am closing this issue now.

**Closed by astoilkov** 2020-10-12 12:49 UTC
Labels: discussion
